apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
  tolerations:
    - effect: NoSchedule
      key: cluster.ocs.openshift.io/openshift-storage
      operator: Exists