apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 01_openshift-storage-namespace.yaml
- 02_openshift-storage-og.yaml
- 03_storage-operator-subscription.yaml
- 04_storage-cluster.yaml
- 05_storage-system.yaml
