apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 01_openshift-storage-namespace.yaml
- 02_openshift-storage-og.yaml
- 03_storage-operator-subscription.yaml
- 04_local-storage-operator.yaml
- 05_auto-discover-devices.yaml
- 06_local-volume-fs.yaml
- 07_local-volume-block.yaml
